### ISSUE TITLE
错误提示

### ISSUE THREAD

**Issue by fronEnd-test** [mkb79/Audible#102]
我在对接注册设备的时候提示{"response":{"error":{"code":"InvalidValue","index":"RYuYsd_4VoiVF34wpxzEJAAAAAAAAAABv_ARlqvxrJ-jPM4mLFcoeH3O84pv6xnbo-wcRzJIxyyhPjBCuewweBAyzdvpHH8pNWKTMsS-INu_7O68uG5-zO2zLPuh4pw3hCpbGWbU0U2E69sXj2DW1Wg23I_GGku1y0pmefIWzfmLwdMkXSDjzkO7OzK3JzmjmcegCPIihpnSNbodgAtiE06b6cfjDnEcaPoTICxuYcXvy1zOOuXsSAYHULgBTO_XXnJHGw==","message":"One or more provided values are invalid."}},"request_id":"67dde610-45d1-4cef-9c3f-fd4f2f58ddf3"}，
请问怎么处理

**Comment by mkb79** [comment]
Hello. Can you provide me your origin request which result in these error message? I can't do anything with this information alone.

**Comment by ysb25536** [comment]
> 你好。您能否向我提供导致这些错误消息的原始请求？单凭这些信息我什么也做不了。

请求地址 https://api.amazon.ca/auth/register

请求参数
{
    "requested_extensions": ["device_info", "customer_info"],
    "cookies": {
        "website_cookies": [],
        "domain": ".amazon.ca"
    },
    "registration_data": {
        "domain": "Device",
        "app_version": "3.76.3",
        "device_type": "A2CZJZGLK2JJVM",
        "device_name": "%FIRST_NAME%%FIRST_NAME_POSSESSIVE_STRING%%DUPE_STRATEGY_1ST%Audible for iPhone",
        "os_version": "15.1.1",
        "device_serial": "Kz0WPCB0688dgF2JkkHNb3LeKsSaGX62Rs2BAbh1",
        "device_model": "iPhone",
        "app_name": "Audible",
        "software_version": "37603817"
    },
    "auth_data": {
        "client_id": "4b7a305750434230363838646746324a6b6b484e62334c654b735361475836325273324241626831234132435a4a5a474c4b324a4a564d",
        "authorization_code": "ANKxpILvMEPNAKvXxsbksmGi",
        "code_verifier": "kspa0g0sxHBt7pa-VhueP04iZ9l8OUMj4OtmBT6zgHQ",
        "code_algorithm": "SHA-256",
        "client_domain": "DeviceLegacy"
    },
    "user_context_map": {
        "frc": "AFQ7rRqrzeV5FbykyVzCM9Sm\/s+gvpBWsk6gh9JCKJzlIONY9ZppO6aa2SIk7vP3lF8DWRYQsIepZDLOfHvzSrZAAU3Cb0DuLuACETdmGcqtvMVoMdFWCXJ6Djk7RyFwnvc9DOV5zJXOsEB1qC0E5IPHqvIBMTPubHcHBKgZiFuB9E30MmEIcMcK6t\/\/YNZwetm+PSY5BM1OiUOUg7p4LqzmtqHgfoGuix+nTcojnAFujaqlz2NJPLAldPs1YMXtQZ4ahgrv+XdNLpiYTDzCLdUEYiQ2ZK96lh7yy6GYaCntySPW5i\/cURwjc8xuf0gLosdYp7CQK3+wIns3k4MyQeCSV59nWyplQRyGLVNio17XgZqwngvOTA7\/liqHDbgX3yZI91EBqcw6"
    },
    "requested_token_type": ["bearer", "mac_dms", "website_cookies"]
}

**Comment by ysb25536** [comment]
> Hello. Can you provide me your origin request which result in these error message? I can't do anything with this information alone.

好像是code导致的，有的账号能注册，有的账号注册不了

**Comment by mkb79** [comment]
It seams that you are using your own implementation! The app_version, os_version and software_version are different than my. That’s make it difficult to solve your issue. 

I suspect there is a problem with the authorization_code and the code_verifier. They are depend on each other.

**Comment by ysb25536** [comment]
> 



> It seams that you are using your own implementation! The app_version, os_version and software_version are different than my. That’s make it difficult to solve your issue.
> 
> I suspect there is a problem with the authorization_code and the code_verifier. They are depend on each other.

我可以看看你的版本参数吗？我试一试

**Comment by mkb79** [comment]
https://github.com/mkb79/Audible/blob/f213edfec5cc4a871b1d65719d38a28df33e1f56/src/audible/register.py#L32

**Comment by ysb25536** [comment]
> https://github.com/mkb79/Audible/blob/f213edfec5cc4a871b1d65719d38a28df33e1f56/src/audible/register.py#L32

你好，请问用python哪个版本执行？

**Comment by mkb79** [comment]
You should have Python 3.6.0 at least. I would prefer Python >= 3.8.

**Comment by ysb25536** [comment]
> You should have Python 3.6.0 at least. I would prefer Python >= 3.8.

你好，我是一名前端开发，我不是很熟悉python，请问有JavaScript版本的吗

**Comment by ysb25536** [comment]
> You should have Python 3.6.0 at least. I would prefer Python >= 3.8.

我尝试在login.py文件运行，但是我启动就在报错
![image](https://user-images.githubusercontent.com/14371960/181195669-64d20065-9431-4774-9313-f0410873987d.png)

**Comment by ysb25536** [comment]
![image](https://user-images.githubusercontent.com/14371960/181204942-869e09e3-6cee-414e-bcb4-9de8a86880ab.png)


> > You should have Python 3.6.0 at least. I would prefer Python >= 3.8.
> 
> 你好，我是一名前端开发，我不是很熟悉python，请问有JavaScript版本的吗

你好，这些包是不是已经过时了？

**Comment by mkb79** [comment]
https://audible.readthedocs.io/en/latest/intro/getting_started.html

**Comment by mkb79** [comment]
Do you use a VPN?

**Comment by ysb25536** [comment]
> Do you use a VPN?

对的

**Comment by ysb25536** [comment]
> > Do you use a VPN?
> 
> 对的

可以加你联系方式请教一下你吗？

**Comment by mkb79** [comment]
What is the purpose of your program? Is it open source? Is it used for commercial purposes?

**Comment by ysb25536** [comment]
> What is the purpose of your program? Is it open source? Is it used for commercial purposes?

我做学习项目

**Comment by ysb25536** [comment]
> What is the purpose of your program? Is it open source? Is it used for commercial purposes?

我把你的项目跑起来了 ，注册设备还是出错
