### ISSUE TITLE
Quality is set to `Extreme` even set to `high`

### ISSUE THREAD

**Issue by nanu-c** [mkb79/Audible#103]
**Describe the bug**
When i try to download high quality books it fails with:
`error: Bad Request (400): 1 validation error detected: Value 'Extreme' at 'quality' failed to satisfy constraint: Member must satisfy enum value set: [High, Normal]` 

if i set the quality to `normal` it works. Further, the `--ignore-errors` is ignored

**To Reproduce**
run `audible download --all --aaxc --cover --cover-size 1215 --chapter -y -q high --ignore-errors`

**Expected behavior**
Download the audiobooks

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: audible-cli, version 0.2.0

**Comment by mkb79** [comment]
https://github.com/mkb79/Audible/discussions/101
