### ISSUE TITLE
Extract Audible Bookmark Notes

### ISSUE THREAD

**Issue by EddyDavies** [mkb79/Audible#107]
**Is your feature request related to a problem? Please describe.**
I love making notes while I am listening to a book on audible, great to attach it to a timestamp for each re-listening of the relevant content but these notes are no use to me if I can't move them to my notes application.

**Describe the solution you'd like**
Simple API access to the note I have made with timecode of note and ideally a link back to audible app at that timecode.

**Describe alternatives you've considered**
Copying out the notes by hand or just making the notes outside the platform but this will lose the context of the time code, copying time codes by hand into another app seems to tedious to be worthwhile.

**Comment by mkb79** [comment]
You can receive Audible Bookmarks and Notes requesting the [sidecar](https://audible.readthedocs.io/en/latest/misc/external_api.html#get-https---cde-ta-g7g.amazon.com-FionaCDEServiceEngine-sidecar).

Using my packages a request look like:

```python
…
asin = XXXXXXXXXX
url = f"https://cde-ta-g7g.amazon.com/FionaCDEServiceEngine/sidecar"
params = {
    "type": "AUDI",
    "key": asin
}
r = client.get(url, params=params)
```

**Comment by EddyDavies** [comment]
This was exactly what I was looking for, I should have found it so thank you for highlighting. Much appreciated!

**Comment by mkb79** [comment]
Great to hear that. You can try my [audible-cli](https://github.com/mkb79/audible-cli) command line app. With these app you can run `audible download --all --annotation` to download all your bookmarks and notes (if available).
