### ISSUE TITLE
Marketplaces

### ISSUE THREAD

**Issue by ts65** [mkb79/Audible#11]
Could you please add Australian and Italian marketplaces:

`
    "australia": {
        "countryCode": "au",
        "domain": "com.au",
        "marketPlaceId": "AN7EY7DTAW63G"
    },
    "italy": {
        "countryCode": "it",
        "domain": "it",
        "marketPlaceId": "A2N7FU2W2BU2ZC"
    },
`

Thanks!

**Comment by mkb79** [comment]
If you take a look in the development tree on github you will see that I added all audible localizations.

In the meantime please read https://github.com/mkb79/Audible#localizations. You can use custom `Locale` class.

You can change your script like this:

```python
italy = audible.Locale(
    countryCode="it",
    domain="it",
    marketPlaceId="A2N7FU2W2BU2ZC",
)

australia = audible.Locale(
    countryCode="au",
    domain="com.au",
    marketPlaceId="AN7EY7DTAW63G",
)

auth = audible.FileAuthenticator(..., locale=italy)
```

**Comment by mkb79** [comment]
Some hints to work with multiple marketplaces. 

Your device registration data can be used with any audible marketplace. To instant switch marketplace without a new Client instance you can do this:

```
import audible

api_italy = "https://api.audible.it"
api_australia = "https://api.audible.com.au"

auth = audible.FileAuthenticator(FILENAME)
client = audible. AudibleAPI(auth)

# now switch api root url
client.api_root_url = api_italy

# make some requests to italy api endpoint
response = client.get(...)

# now switch api root url again
client.api_root_url = api_australia

# make some requests to australia api endpoint
response = client.get(...)
```

Hope this makes it easier for you. 

Greets

**Comment by ts65** [comment]
Nice, thank you! The API switching helps a lot
