### ISSUE TITLE
Lift upper version restriction on `httpx`.

### ISSUE THREAD

**Issue by dreirund** [mkb79/Audible#123]
Currently, the metainformation to this software says that the required `httpx` needs to be a version lower than 0.24.0 (see, for example, `setup.py`).

But currently, 0.24.0 is out.

So can you lift that restriction? Maybe do not restrict the upper version at all?

Regards!

**Comment by mkb79** [comment]
I'll remove the upper bound in [this](https://github.com/mkb79/Audible/tree/116-switch-to-poetry-implement-ci+cd-remove-python-version-38) branch.

I'll merge this when it’s ready.

**Comment by mkb79** [comment]
The upper restriction for `httpx` now have been removed in this package. So I'll feel free to close this issue now.
