### ISSUE TITLE
Is there any way to get a list of books in a series?

### ISSUE THREAD

**Issue by physxP** [mkb79/Audible#124]
**Is your feature request related to a problem? Please describe.**
I have been trying to get all the books in a given series. I can get the series ASIN in the search query on https://api.audible.com/1.0/catalog/products endpoint but don't know where to go from here. Since Audible does provide us with a page with all the books in series for example: https://www.audible.com/series/A-Song-of-Ice-and-Fire-Audiobooks/B006K1QER6, so it may be possible to get an endpoint?

**Describe the solution you'd like**
If we can find atleast an endpoint that provides a list of books in a series then that would be great!

**Describe alternatives you've considered**
One option is to get the url of the series and parse the html to get the list of books but that solution doesn't feel very good. Another option would be to search in the `1.0/catalog/products` by series name and filter out the results. I don't know how well that would work in practice.

**Additional context**
N/A

**Comment by mkb79** [comment]
The episodes of a series can be searched via the [catalog/products/sims](https://audible.readthedocs.io/en/latest/misc/external_api.html#get--1.0-catalog-products-(string-asin)-sims) endpoint.

You have to provide the `similarity_type= InTheSameSeries` query parameter. 

The full url looks like `https://api.audible.XX/1.0/catalog/products/XXXXXXXXXX/sims?image_sizes=360,408,252,1215,882,570,315,558,900&response_groups=relationships,media,customer%5Frights,product%5Fplan%5Fdetails,sample,rating,sku,badges,contributors%2Cproduct%5Fdesc,product%5Fplans,product%5Fextended%5Fattrs,product%5Fattrs&similarity_type=InTheSameSeries&reviews_sort_by=MostHelpful&num_results=50`.
