### ISSUE TITLE
I need some help with metadata

### ISSUE THREAD

**Issue by soulkkkkk** [mkb79/Audible#180]
www.amazon.com/-/zh/ap/signin?openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3F_encoding%3DUTF8%26ref_%3Dnav_ya_signin&openid.identity= http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=usflex&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid. ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0

Hello, thank you for your tool. I used XXTEA to generate metadata1, and then submitted it to the above URL to log in to our Amazon account in batches. However, after submission, the page should normally return to the WEB(PC) login page. But I often return to the mobile login page. When I use it, I pass in 2 parameters
(Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.42) and the link address above.

, respectively user-agent and the URL above. If I want to specify a return to the web(PC) login page, how should I adjust it? Am I using the right method?

**Comment by mkb79** [comment]
Thank you for open this issue.

You can try to change the `ref_` url query param from `nav_ya_signin` to `nav_signin`. This should solve your issue. 

FYI:
You can try to set `metadata1` to `false` instead of using XXTEA to encrypt your own metadata. In most cases this will work without any exceptions.

**Comment by mkb79** [comment]
Does the issue still exist?
