### ISSUE TITLE
Audible brazil

### ISSUE THREAD

**Issue by mkb79** [mkb79/Audible#194]
Audible now has a new marketplace on www.audible.com.br. 

Need to implement this in this package.

**Comment by mkb79** [comment]
Until the Brazilian marketplace is hardcoded in my package it can be used these way:

```python
from audible.localization import Locale

brazil_locale = Locale("br", "com.br", "A10J1VAYUDTYRN")
```

Now you can use the `brazil_locale` as `locale` keyword so:

```python
from audible import Authenticator, Client, AsyncClient

# login
login = Authenticator.from_login(…, locale=brazil_locale)

# login external
login_external = Authenticator.from_login_external(locale=brazil_locale, …)

# load credentials
auth = Authenticator.from_file(…, locale=brazil_locale)
```

**Comment by mkb79** [comment]
The Brazilian marketplace can be tested out using TestPyPI with these command

```shell
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ audible==0.8.3.dev1695285418
```

**Comment by fcarreira66** [comment]
Thanks for your Audible's support to Brazilian marketplace. Is there anything to do in Audible-cli's code to support it? Even using Audible development version 0.8.3, Audible-cli does not recognise Audible BR.

**Comment by mkb79** [comment]
I does not know that you want to use `audible-cli`. The `brazil` marketplace must be implemented there. I will rework `audible-cli` soon to create the marketplaces dynamically from the `audible` package. 

In the meantime you can change the source code of the following files in `audible-cli`:

1. `cmds/cmd_manage.py`
2. `cmds/cmd_api.py`
3. `cmds/cmd_quickstart.py`

In each of these files are exist one line(s) `["us", "ca", "uk", "au", "fr", "de", "es", "jp", "it", "in"]`.

You have to extend the list with `br`. The result should looks `["us", "ca", "uk", "au", "fr", "de", "es", "jp", "it", "in", "br"]`.

If you modify `audible-cli` these way and install the `audible dev version` in the same venv (if you use a venv) then it will work.

**Comment by mkb79** [comment]
@fcarreira66 
`audible-cli` v0.2.5 is now on PyPI. The update supports dynamically loading of `audible` marketplaces. So you only need to install `audible_cli` and then `audible dev version` into the same venv and it will work.

**Comment by mkb79** [comment]
@fcarreira66 
Another good news. I've updated `audible` to v0.9.0 now. If you reinstall `audible-cli` it will now work out of the box. But make sure that the new audible package is also updated.

**Comment by fcarreira66** [comment]
Wow, I apreciate your effort, thank you!
But, it seems that Audible BR is not working (yet) for login via external browser (I am using Audible-cli version 0.2.5 and Audible version 0.9.0).

When I ran Audible-Cli and chose external browser, the link was generated and the response of Audible BR site was: https://www.amazon.com.br/ap/404

When I typed my credentials (Amazon BR's login and password), audible-cli exited with error:
Login with amazon to your audible account now.
Captcha found
Open Captcha with default image viewer [Y/n]: y
Answer for CAPTCHA: ******
2FA is activated for this account.
Please enter OTP Code: ******
Uncaught Exception
Traceback (most recent call last):
  File "C:\Users\My_login\AppData\Roaming\Python\Python311\site-packages\audible_cli\cli.py", line 60, in main
    sys.exit(cli(*args, **kwargs))
  File "C:\Users\My_login\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\My_login\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\My_login\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\My_login\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\My_login\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\My_login\AppData\Roaming\Python\Python311\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\My_login\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\My_login\AppData\Roaming\Python\Python311\site-packages\audible_cli\cmds\cmd_quickstart.py", line 162, in cli
    build_auth_file(
  File "C:\Users\My_login\AppData\Roaming\Python\Python311\site-packages\audible_cli\utils.py", line 102, in build_auth_file
    auth = Authenticator.from_login(
  File "C:\Users\My_login\AppData\Roaming\Python\Python311\site-packages\audible\auth.py", line 408, in from_login
    login_device = login(
  File "C:\Users\My_login\AppData\Roaming\Python\Python311\site-packages\audible\login.py", line 491, in login
    raise Exception("Login failed. Please check the log.")
Exception: Login failed. Please check the log.

Is there a log file for this? Where is it location?
Again, I am really thanksful for your help.

**Comment by mkb79** [comment]
@fcarreira66 
I've to look deeper into this issue. 

In the meantime you can use the `us` locale for the quickstart. Then go to the config dir and change the `country_code` in the `config.toml` file to `br`.

**Comment by mkb79** [comment]
@fcarreira66 
If you update `audible` to v0.9.1 then you are now able to login to brazilian marketplace. External login will not work without additional user work.

**Comment by fcarreira66** [comment]
Yes, thank you! It worked with audible v.0.9.1. I ran _****audible quickstart**_** with my Audible BR's credentials and I got it. Not tested with external login via browser.

**Comment by mkb79** [comment]
Great to hear that. I'll close this issue now. Please open a new one if you encounter in any other issue.
