### ISSUE TITLE
PDF URL

### ISSUE THREAD

**Issue by ts65** [mkb79/Audible#23]
I'm trying to use the pdf_url value from the `GET /1.0/library/%{asin}` endpoint. It worked before, but currently the value is a cloudfront.net URL. However, the URL is missing the Key-Pair-Id and Policy query parameters, so using the URL results in an error message. Do you know how to get a working URL with these parameters?

**Comment by mkb79** [comment]
Yeah, there are some changes on the pdf url obtained from api. Some credentials in url params are missing. 


Here is a workaround:

```python
import audible
import httpx

auth = audible.FileAuthenticator(...)

# top level domain of the api you have selected, e.g. "de"
tld = "TLD"
asin = "ASIN_FROM_BOOK"

with httpx.Client(auth=auth) as client:
    resp = client.head(
            f"https://www.audible.{tld}/companion-file/{asin}"
    )
    url = resp.url
```

Then you can download the pdf with the url. Or simple use `client.get` instead of `client.head` to download the file immediately.

**Comment by ts65** [comment]
Thank you, that works fine. I've seen the companion-file URL but didn't know that I can use the authenticator as auth parameter.

**Comment by mkb79** [comment]
Works the workaround for you? If so, I would close this issue.

**Comment by mkb79** [comment]
Oh we wrote at the same time. Than I close this issue now. 

Best regards

**Comment by mkb79** [comment]
It is possible to rework :met:`audible.auth. BaseAuthenticator. auth_flow` so it uses the website cookies in addition. So you could parse the whole audible and amazon webpage.

The website cookies are limited to specific tld. You can get new website cookies for a specific tld with :func:`audible.auth. refresh_website_cookies`.

**Comment by pishposhmcgee** [comment]
I have found recently that HEAD requests are being rejected (405 method not allowed error). My workaround has been to change to something like the following:

```
import audible
import httpx

auth = audible.FileAuthenticator(...)

# top level domain of the api you have selected, e.g. "de"
tld = "TLD"
asin = "ASIN_FROM_BOOK"

with httpx.Client(auth=auth) as client:
    resp = client.get(
            f"https://www.audible.{tld}/companion-file/{asin}"
    )
    # unnecessary if you don't need to know the final URL
    url = resp.next_request.url.raw
    resp=client.session.send(resp.next_request)
```

This might be redundant, too. If you're already following redirects you probably don't have to change anything.
