### ISSUE TITLE
Expose New Approval Alerting Callback

### ISSUE THREAD

**Issue by CuriousEl3phant502** [mkb79/Audible#28]
Great project! Thanks so much for all the hard work. :) 

I recently ran into the issue of approval alerting (that amazon recently added) and it was already fixed! Wow.

I wanted to see if you could expose the alert callback similar to OTP, CVF, etc.? That would be much appreciated, thanks!

**Comment by mkb79** [comment]
Thank you for liking this package!

I will implement your future request as fast as possible. It‘s not a hard work to do it.

**Comment by mkb79** [comment]
Can you tell me, if this is okay for you. When you have some enhancements to this pull request I can implement this.

**Comment by CuriousEl3phant502** [comment]
Thanks for such a quick response! I tried to test this, but it looks like after getting past this initially I was unable to trigger it again- even on another computer. I was waiting to fully test on another comp this weekend, but looks like the same result. It looks like it will work just fine though. :)
