### ISSUE TITLE
Only getting part of the CAPTCHA image

### ISSUE THREAD

**Issue by jeromegit** [mkb79/Audible#34]
Intead of a typical CAPTCHA image that looks like this:
![image](https://user-images.githubusercontent.com/552382/105618487-8f932a80-5d9c-11eb-978b-039b50bf465e.png)
I'm now getting a partial image like this:
![image](https://user-images.githubusercontent.com/552382/105618500-b2254380-5d9c-11eb-97c8-bce69b9072ad.png)

I haven't change anything to my code. The only difference is that I've upgraded to a Mac Mini M1 (vs an old Mac Mini 2012) which came with Bigsur (vs Catalina).
My old Mac is no longer available for me to test. :-(

**Comment by mkb79** [comment]
I had the same issue some times ago. The problem goes away as I logged in some days later.

You can go around with a captcha callback like this:
    
```python

import audible


def captcha_callback(captcha_url: str) -> str:
    print("Please open the captcha url in a webbrowser of your choice.")
    print(captcha_url)

    guess = input("Answer for CAPTCHA: ")
    return str(guess).strip().lower()


auth = audible.Authenticator.from_login(..., captcha_callback=captcha_callback)

```

Or you can use the external login with:

```python

import audible

auth = audible.Authenticator.from_login_external(locale="LOCALE_CODE")

```

**Comment by jeromegit** [comment]
Thanks for the quick response, @mkb79 !
The external login didn't work for me. When I tried to copy the (long) URL as prompted, maybe because it was too long but pressing Enter didn't work; the script wouldn't take the URL.
I removed the external login code and all of a sudden, the captcha started to work again.
I'm all good now.

**Comment by mkb79** [comment]
Your issue with the external login seams the same as in [issue-32](https://github.com/mkb79/Audible/issues/32).

It‘s good to hear that your captcha issue is gone away. I can advise you to register a Audible device with my package. So you don’t need to login ever again.

**Comment by mkb79** [comment]
If you are interested in using the external login you can read [here](https://stackoverflow.com/questions/7357007/python-raw-input-limit-with-mac-os-x-terminal)! The problem seams to be Mac OS related. You can try to import readline module. Maybe this solves the issue. If it helps please report to me so I can post the solution to issue-32.

**Comment by jeromegit** [comment]
Hi @mkb79 
Sorry for the late response.
Adding the readline module did the trick for me.

Thanks!

**Comment by mkb79** [comment]
@jeromegit Thank you for this very useful information!
