### ISSUE TITLE
Australia problems authorizing new device fails

### ISSUE THREAD

**Issue by openaudible** [mkb79/Audible#37]
I'm having problems getting this to work in the Australia Marketpace. Not sure if its just me or everyone.
I am able to log in, but authorizing a new device returns an error.  Other regions are working fine. 

```
resp = httpx.post(f"https://api.amazon.{domain}/auth/register", json=body)
```
Get error 400 BAD REQUEST from:

Exception: {'response': {'error': {'code': 'InvalidToken', 'index': 'cXZ_xxxx_z95BIfA==', 'message': 'One or more tokens are invalid.'}}, 'request_id': '81d134e1-c0f9-4a83-8dce-xxxx'}

I verified that a device isn't created at: 
https://www.amazon.com.au/hz/mycd/digital-console/devicedetails?deviceFamily=AUDIBLE_APP

But able to log in and register a device from the android app. 

Trying to figure out a way to debug.. Was wondering if there is another Amazon API call that we can call to check that the session was established? Anyway, happy to provide more details or help debug if I can.

**Comment by mkb79** [comment]
The error code say, that the access token from login is not accepted. Can you try login with `auth = Authenticator.from_external_login("au")`. 

Afterwards register with auth.register()

**Comment by mkb79** [comment]
I can verify that there is some problem register a new device in Australia. I‘ve got the same error code. I will test out more. 

If you have books on or don’t take care about login to other marketplaces you can use another country code for login and register. After that change the `locale code` in auth file to au and remove website cookies (they are not valid for Australia marketplace)!

```python
import audible

auth = audible.Authenticator.from_file(...)
auth.website_cookies = None
# or fetch new ones for Australia
auth. set_website_cookies_for_country("au")
auth.locale = "au"
auth.to_file()
```

**Comment by mkb79** [comment]
I have identified the problem. Amazon Australia handles access_token check differently. 

The access_token contains the device_serial which where used at login. And the device_serial doesn‘t match with the device_serial from login.

I will fix this as soon as possible.

**Comment by mkb79** [comment]
I‘ve added a PR now. I can register a new device on Australia marketplace with this. Need test for other marketplaces. 

I implemented a serial generator which generates a 32 bytes serial. iPhone has typical 40 bytes. But the login and register running fine. Have to take a look at this.

**Comment by openaudible** [comment]
Wow. Nice fix. Will report back!

**Comment by openaudible** [comment]
Great work. 

I verified things work in multiple regions. 

I used a 40 hex digit (lower case) device ID for the iphone and passed the whole string to the openid login request (prepended with "device:") and that worked. Don't think you need or want to append the "#A2CZJZGLK2JJVM".

I'm not a python developer, so can't provide much other feedback. (OpenAudible developers use java.)

I did see an instance where your message: "Approval alert detected! Amazon sends you a mail" was used when Amazon actually sent a text message with a link to the confirm URL. So might need to change that to "email or text message". 

Owe you a beer or coffee.. Or more. Closing as fixed.

**Comment by mkb79** [comment]
I wanted to be close to the iOS Audible app. The iOS App uses the serial + "#" + the device type to build the device id. 

That‘s the same for the Kindle and the Alexa App. Using the serial only may be running fine for now. But there is no quarantee that this would be not changed like the problem above. Amazon Australia changed the access token check some weeks ago. 

Thanks for you advice with the approval alert. 

Cheers with a beer ...

**Comment by openaudible** [comment]
Ah- didn’t catch what that # number was. That bug would have taken me weeks. Just released a beta of OpenAudible with the fix. Let me know if you want a license or some $. OpenAudible at email dot tg.  Thanks.

**Comment by mkb79** [comment]
@openaudible
I wrote a mail to you yesterday!
