### ISSUE TITLE
PyCrypto and Windows

### ISSUE THREAD

**Issue by joefazz** [mkb79/Audible#4]
Hi!

I was looking to use this package but when I tried to install it Windows throws an ugly error message caused by the pycrypto `setup.py`. Looking up how to resolve this issue wasn't very helpful as it seems that [pycrypto is dead](https://github.com/dlitz/pycrypto/issues/238). 

I'm sure I can find a workaround but I thought it might be worth making an issue as it's probably not great to be using a corpse of a library as a dependency. If there's not interest in it then fair enough and the issue can just be closed.

Thanks!

**Comment by mkb79** [comment]
You are right, pycrypto is dead. But I write the code with Pythonista for iOS. So I‘m limited to pycrypto. I can’t install pycryptodome on Pythonista. 

On windows you have to install  Microsoft Visual Studio Build tools and patch some code (https://stackoverflow.com/questions/41843266/microsoft-windows-python-3-6-pycrypto-installation-error)!

But here is a workaround for windows:

```python

pip uninstall pycrypto
pip install --no-deps audible
pip install pycryptodome aiohttp beautifulsoup4 pbkdf2

```

**Comment by joefazz** [comment]
Thanks for the in depth reply. I understand the reason it's used now. Thanks for the workaround as well!

**Comment by mkb79** [comment]
Switched from pycrypto to pyaes. See [release v0.2.1a3](https://github.com/mkb79/Audible/releases/tag/v0.2.1a3)
