### ISSUE TITLE
Whispersync for voice? 

### ISSUE THREAD

**Issue by flo62134** [mkb79/Audible#43]
Hi!

Thanks a lot for the hard work on this!
I also am a big fan of Audible and Kindle.
I tend to buy the Kindle and Audible versions of the same book.

Although, whispersync for voice is not available in my country.
However, the books I buy definitely support Whispersync for voice.

I'm looking for a homemade way to synchronize my Kindle and Audible books.
Would your API be of any help to achieve my goal?

Thanks for your help!

**Comment by mkb79** [comment]
Hi,

Audible and Kindle synchronize there settings using a special endpoint (https://cde-ta-g7g.amazon.com/FionaCDEServiceEngine/sidecar) or using the whispersync api endpoint (https://api.amazon.com/whispersync/v2/). 

Theoretically it is possible to do what you want. But you must know how to build the request (query params, headers and body)! A sidecar request body is xml v1 encoded.

To help you a bit more I need to know which data you want to be to synchronize? Bookmarks, clips, positions?

**Comment by flo62134** [comment]
> Hi,
> 
> Audible and Kindle synchronize there settings using a special endpoint (https://cde-ta-g7g.amazon.com/FionaCDEServiceEngine/sidecar) or using the whispersync api endpoint (https://api.amazon.com/whispersync/v2/).
> 
> Theoretically it is possible to do what you want. But you must know how to build the request (query params, headers and body)! A sidecar request body is xml v1 encoded.
> 
> To help you a bit more I need to know which data you want to be to synchronize? Bookmarks, clips, positions?

Thanks a bunch for answering my questions!

What I would love to do:
- Read the same book (same ASIN, same account, same store) on Kindle and Audible.
- Progress through the book/audiobook by reading/listening to it
- Retrieve the corresponding position on the medium that I've the least read (the least progression)
- Go to this specific position on the medium that I've the least read 

Basically, I would like to recreate the same behavior as Whispersync for voice!
What could this project help me with?

**Comment by mkb79** [comment]
You have to register a Kindle device to obtain special data for further authentication. You can take a look on my [Kindle](https://github.com/mkb79/kindle) package for Python. 

If you have you auth data, you can make authenticated requests.

```python
import httpx
import kindle

auth = kindle.Authenticator.from_file(...)
client = httpx.Client(auth=auth)

asin = 'ASIN OF YOUR BOOK'

# gives you some book infos
r = client.get(f'https://sars.amazon.com/sidecar/sa/EBOK/{asin}').json()

# gives you bookmarks and notes
params = {
    'type': 'EBOK',
    'key': asin,
    'guid': 'Can be obtained by downloading the manifest of the book'.
}
r = client.get('https://cde-ta-g7g.amazon.com/FionaCDEServiceEngine/sidecar', params=params)

# create bookmarks, notes, positions
# content type is application/x-octet-stream
body = '''<?xml version="1.0" encoding="UTF-8" ?>
<annotations timestamp="2021-04-03T20:00:00" version="1.0"><book guid="..." key="..." type="EBOK" version="0" format="YJBinary"><last_read begin="257182" pos="257182" state="" timestamp="2021-04-03T20:00:00"><metadata><![CDATA[<<UNSET>>]]></metadata></last_read><note action="cremet" begin="258825" end="258825" pos="258825" state="" timestamp="2021-04-03T20:46:13">fake note<metadata><![CDATA[<<UNSET>>]]></metadata></note></book></annotations>'''
r = client.post('https://cde-ta-g7g.amazon.com/FionaCDEServiceEngine/sidecar', data=body)
```

That’s what I could find out in short time (sync notes, bookmarks and co is new for me)!

**Comment by mkb79** [comment]
Can I close this issue now?

**Comment by flo62134** [comment]
> Can I close this issue now?

Thank you very much for your help, I appreciate it!
I'll close this issue 👍
