### ISSUE TITLE
is_valid_email have bug,Pls check it

### ISSUE THREAD

**Issue by pengpengker** [mkb79/Audible#46]
**Describe the bug**
If your email address has “-”，It will not be allowed to pass the is_valid_email  inspection！
For example:123456@t-mobile.de  it no work！

login.py 222 line
def is_valid_email(obj: str) -> bool:
    valid_mail = r"^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w+$"
    if re.match(valid_mail, obj):
        return True
    return False

It should be changed to:^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$

**Comment by mkb79** [comment]
@pengpengker Thank you for opening this issue

@eode Thank you for your code snippet. I'm not really sure what I should do. I could remove the email validation part or I could implement your code and add `email_validator` as a dependency.

**Comment by pengpengker** [comment]
> Also running into this issue. However, the suggested regex is bad, as it _requires_ the address to be a dotted atom.
> 
> Honestly, in general, the real technical specs of email-local and hostname validation (vs domain name validation vs labels vs .. .. ...) can be quite complex.
> 
> If you _really_ want to use a regex, this might work:
> 
> ```python
> valid_mail = "^[-a-zA-Z0-9!#$%&'*+/=?^_`{|}~]+(\.[-a-zA-Z0-9!#$%&'*+/=?^_`{|}~]+)*@[\w-]+[.][\w-]+([.][\w-]+)*$"
> 
> # or
> text_atom = r"[-a-zA-Z0-9!#$%&'*+/=?^_`{|}~]"
> valid_mail = fr"^{text_atom}+(\.{text_atom}+)*@[\w-]+[.][\w-]+([.][\w-]+)*$"
> ```
> 
> That regex is _probably_ going to catch most issues, and _probably_ be lenient enough to permit all valid email addresses.
> 
> ..but, you could also forego most errors, and this issue coming up again (in all likelihood) and use the package.`email_validator`
> 
> ```python
> from email_validator import validate_email, EmailNotValidError
> 
> def is_valid_email(obj: str) -> bool:
>     try:
>         validate_email(obj, check_deliverability=False)  # use True to validate over the net
>         return True
>     except EmailNotValidError as error:
>         print(error)  # if you want to describe to the user why it's broken
>         return False
> ```
> 
> Yes, it's a third-party module, but it wraps considerable complexity, and it's better to standardize where.. ..well.. ..standards are concerned.
> 
> On the complexity of email addresses: http://rumkin.com/software/email/rules.php
> On Text Atoms: https://serverfault.com/questions/395766/are-two-periods-allowed-in-the-local-part-of-an-email-address

Thank U，it work. Hurray for u

**Comment by W-rakuda** [comment]
I also have this issue. 
Many use tags with their gmail addresses, like this:
myname+work@gmail.com
myname+leisure@gmail.com

My Audible username has a tag like this, so I am not able to log in.

**Comment by mkb79** [comment]
v0.5.5 solve this issue now
