### ISSUE TITLE
CVF page has changed

### ISSUE THREAD

**Issue by rmcrackan** [mkb79/Audible#47]
Heads up: a user of Libation got a CVF approval page without div id resend-approval-alert. Look for one of these also:

form id="resend-approval-form" method="post" action="/ap/cvf/approval/resend"

a id="resend-approval-link" class="a-link-normal" href="#"

**Comment by W-rakuda** [comment]
Yes, this is an issue for me as well. The login fails at the same time I get an approval email from audible.

**Comment by mkb79** [comment]
I will close this issue now.
