### ISSUE TITLE
downloading cover art? 

### ISSUE THREAD

**Issue by PHDPeter** [mkb79/Audible#48]
Just started using this API and wondered if there is a way to download the cover art for books too?
There is a value 'image_url' but it seems to be None for every book.
Any help would be awesome thanks.

**Comment by mkb79** [comment]
Hi,

you have to provide the correct `response_group` to your request. Take a look [here](https://audible.readthedocs.io/en/latest/misc/external_api.html#get--1.0-library)!

The `response_group` for the cover is `media` or `product_attrs`, I think. Best is, you provide all available on your request!

**Comment by mkb79** [comment]
Can I close this issue now?

**Comment by PHDPeter** [comment]
Ow yes, sorry 100% solved
