### ISSUE TITLE
Advanced stats

### ISSUE THREAD

**Issue by Chogos** [mkb79/Audible#495]
I wonder if anyone knows how to get advanced stats from the API, like how much time was spent in car mode.
I'd either like to filter the aggregates or if there is a way to get all events. `/1.0/stats/events` doesn't seem to support `GET`.

**Comment by mkb79** [comment]
I've some API records for the years 2023/2024 with GET requests and responses to subendpoints of stats. 

- https://api.audible.com/1.0/stats/status/finished?start_date=2001-01-01T01:00:00%2B0100
- https://api.audible.com/1.0/stats/aggregates?daily_listening_interval_duration=7&daily_listening_interval_start_date=2024-04-11&monthly_listening_interval_duration=7&monthly_listening_interval_start_date=2023-10&response_groups=total_listening_stats&store=Audible
- https://api.audible.de/1.0/stats/continuelistening?store=Audible

For `https://api.audible.com/1.0/stats/events` I've found only PUT requests.

**Comment by Chogos** [comment]
Thanks, but the responses I got for my account were mostly gibberish and without anything besides plain listening time.
