### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by NathanTech7713** [mkb79/Audible#5]
I can not install this program as it relies on pycrypto, which is bugged the hell out when ever I try to install it. The issue with pycrypto is well know, and, aparrently, pycrypto has been depricated.

**Comment by mkb79** [comment]
Hi. Look here https://github.com/mkb79/Audible/issues/4. 

The problem is already known.

**Comment by mkb79** [comment]
You can install this release https://github.com/mkb79/Audible/releases/tag/v0.2.1a3
