### ISSUE TITLE
Internal Server Error in get_license_response

### ISSUE THREAD

**Issue by wtkranz** [mkb79/Audible#51]
**Describe the bug**
The subject says it all

**To Reproduce**
Executing download_books_aaxc.py with a valid German account and a book you own.
Result is 
`Error: Internal Server Error (500): There was an internal error processing the request`
in `get_license_response`

I have no experience with http via python so at the moment I do not know how to narrow it down but I am willing to help if somebody can point me in the right direction

**Expected behavior**
Eventually a downloaded book but at the moment I am more interested in the voucher file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 16.04 but heavily upgraded)
 - Python 3.9.6
 - Current git version of Audible

**Comment by mkb79** [comment]
Make sure you have registered a device (and save the credentials) before you make a licenserequest. A registration is needed for the `licenserequest` endpoint. 

If you have registered a device you can try this code:

```python

import base64
import json
import pathlib

import audible
import httpx
from audible.aescipher import decrypt_voucher_from_licenserequest as dv


# files downloaded via this script can be converted
# audible uses a new format (aaxc instead of aax)
# more informations and workaround here:
# https://github.com/mkb79/Audible/issues/3
# especially: https://github.com/mkb79/Audible/issues/3#issuecomment-705262614


# get license response for book
def get_license_response(client, asin, quality):
    try:
        response = client.post(
            f"content/{asin}/licenserequest",
            body={
                "drm_type": "Adrm",
                "consumption_type": "Download",
                "quality": quality
            }
        )
        return response
    except Exception as e:
        print(f"Error: {e}")
        return


def get_download_link(license_response):
    # example download function
    return license_response["content_license"]["content_metadata"]["content_url"]["offline_url"]


def download_file(url, filename):
    with httpx.stream("GET", url) as r:
        with open(filename, 'wb') as f:
            for chunck in r.iter_bytes():
                f.write(chunck)
    return filename


if __name__ == "__main__":
    # These 3 variables must be filled out
    fn = FILENAME_OF_AUTH_FILE
    asin = YOUR_ASIN
    title = TARGET_FILE_AAXC

    auth = audible.FileAuthenticator(
        filename=fn
    )
    client = audible.Client(auth)
    lr = get_license_response(client, asin, quality="Extreme")
    if lr:
        dl_link = get_download_link(lr)
        filename = pathlib.Path.cwd() / title
        print(f"download link now: {dl_link}")
        status = download_file(dl_link, filename)
        print(f"downloaded file: {status} to {filename}")

        voucher_file = filename.with_suffix(".json")
        decrypted_voucher = dv(auth=auth, license_response=lr)
        print(decrypted_voucher)
        voucher_file.write_text(json.dumps(decrypted_voucher, indent=4))
        print(f"saved voucher to: {voucher_file}")
```

This is tested now and running fine!

**Comment by wtkranz** [comment]
Works like a charm. That's something I would never have tried

**Comment by mkb79** [comment]
You are mean the registration? Please make sure to reuse registration data. This prevent you for filling your Amazon devices list on every new registration!

**Comment by wtkranz** [comment]
Thank you for the additional hint. Yes, I totally misunderstood the meaning of 'register' in this context. I had seen it as related to opening an account (which I did not intend to do via python ;) ) as opposed to registering a device. Additionally, I am totally new to Audible and was therefore taken by surprise that it is quite a challenge to get their content on my mp3-player. But now after a small software installation marathon (and thanks to your help) it works
