### ISSUE TITLE
Creating new release with support for newer Python

### ISSUE THREAD

**Issue by jubalh** [mkb79/Audible#510]
Thanks for your project! I'm currently packaging audible-cli and this project for openSUSE.
When packaging I stumbled upon the following: `ERROR: Package 'audible' requires a different Python: 3.12.5 not in '<3.12,>=3.8'`. And saw that for the latest release you require <3.12,>=3.8.
I saw that there have been quite a few commits since the last release and wondered if you plan on creating a new one and could make it work with a more recent Python.

**Comment by mkb79** [comment]
Hi,

yeah, the master branch requires Python >=3.10 and <3.13. I can make a new release with these changes soon. I only need feedback from some testers, if they have some troubles. In my side, the master branch runs fine.

**Comment by mkb79** [comment]
@jubalh 
I've created v0.10.0 right now and published the release on PyPI.
