### ISSUE TITLE
Logging on Info Level for every request

### ISSUE THREAD

**Issue by lars-hoeck** [mkb79/Audible#533]
**Describe the bug**
With audible 10.0.0 on Python 12 get request are logged on info level.

**To Reproduce**
Use Python 12 and audible 10.0.0. Set log level to "Info" and start a request on catalog.
`Example of log: HTTP Request: GET https://api.audible.de/1.0/catalog/products/?asins=B004V0DVVA....`

**Expected behavior**
I would expect requests to be log level debug

**Desktop (please complete the following information):**

- OS: MacOS 14.4.1
- Version python12, audible10

**Additional context**
I went from audible 8.x to 10. Didnt see these logs in 8.x. Went through the changelogs but couldn't see a change of log level.

**Comment by mkb79** [comment]
@lars-hoeck 
My package logs client requests on debug level. You can check [these](https://github.com/mkb79/Audible/blob/96a3641e9d81e9b58fd5a29e76e2d1f0a9a7d46a/src/audible/client.py#L486) and [these](https://github.com/mkb79/Audible/blob/96a3641e9d81e9b58fd5a29e76e2d1f0a9a7d46a/src/audible/client.py#L370) code lines. 
Maybe the log entries are coming from the underlying httpx package. How do you have configured your logger?

**Comment by lars-hoeck** [comment]
I use a simple `logging.basicConfig(format='%(asctime)s %(message)s', level=logging.INFO)`

**Comment by mkb79** [comment]
Please add the following line after your logging.basicConfig line: `logging.getLogger("httpx").setLevel(logging.WARNING)`. 

This should solve your issue!

**Comment by lars-hoeck** [comment]
Thanks
