### ISSUE TITLE
Language parameter for Author endpoint

### ISSUE THREAD

**Issue by lars-hoeck** [mkb79/Audible#551]
I'd like to get the author description in a different language.

I use this endpoint and like to now which parrameter is necessary to change the language
```
client.get(
        "screens/audible-android-author-detail/B000AP9A6K",
        params={
            "author_asin": "B000AP9A6K",
            "title_source": "all"
        },
        headers={
            "X-ADP-SW": "0"
        })
```

I tried it in the app and you can change the app language which will also translate the profile page(I tried it with spanish on J. K. Rowlings page).
Change Language:
Go to profile -> Setting Icon Top Right -> Language -> Open Settings

Would be nice if you could tell me which parameter was set on the author page request.

**Comment by mkb79** [comment]
@lars-hoeck 
I have German language on CA and US marketplace. But I does not have such a language Option on iOS. But I've checked some different`screens` sub-endpoints. Some send an header with `country-code=DEU` and some a param with `country_code=DEU`. You could try setting one of the above and check the result.

**Comment by mkb79** [comment]
@lars-hoeck 
I've tried it myself now and it does not work with `country code`. But I've overseen, that an `Accept-Language` header is set on any `screens` endpoint request, too. And that’s is it. `"Accept-Language": "de-DE"` will set the response to German an `"Accept-Language": "en-US"` to englisch. 

So your code must look:

```python
    client.get(
        "screens/audible-android-author-detail/B000AP9A6K",
        params={
            "author_asin": "B000AP9A6K",
            "title_source": "all"
        },
        headers={
            "X-ADP-SW": "0",
            "Accept-Language": "de-DE"
        })
```

**Comment by lars-hoeck** [comment]
Thanks a lot, works like a charm.
