### ISSUE TITLE
MyAudible project

### ISSUE THREAD

**Issue by mkb79** [mkb79/Audible#63]
I'm working on my new project [MyAudible](https://github.com/mkb79/myaudible). I have no experience with Django. Everyone is welcome to help me building a good Django app!

**Comment by bottydim** [comment]
Hey @mkb79,

First, YOU ROCK!! This is the coolest thing I have seen in a while! I have been looking for the audible API for years now!
Second, what is the functionality you are looking to build into the Django app?

I am looking for ways to (1) get more detailed stats and (2) export my bookmarks, so that I can review them more easily.

**Comment by mkb79** [comment]
Hi @bottydim 

for a way to export your bookmarks, clips and notes take a look [here](https://github.com/mkb79/audible-cli/discussions/73). This will give you the information you want. 

What detailed stats you want? Maybe I can give you the right API endpoint for this. 

My plan was to porting my `audible-cli` package to Django to show the output on nice webpages. The main goal are to let the user show there library with nice additional information and let them download the decrypted files.

**Comment by bottydim** [comment]
Hey @mkb79,

Thank you very much for the great pointer! I have implemented v1 examples of both detailed stats #90 and downloading bookmarks #91 
Honestly, you have the coolest repo in the world! 😄 

This is a great start for the Django app. Maybe we can merge it with the PRs I just made and we can make a cool dashboard where you can see your stats, bookmarks, download or even play the audiobook while taking notes.

**Comment by mkb79** [comment]
Hi @bottydim,

> Thank you very much for the great pointer! I have implemented v1 examples of both detailed stats https://github.com/mkb79/Audible/pull/90 and downloading bookmarks https://github.com/mkb79/Audible/pull/91

Thank you for helping me out! I've merged your pull requests. 

> This is a great start for the Django app. Maybe we can merge it with the PRs I just made and we can make a cool dashboard where you can see your stats, bookmarks, download or even play the audiobook while taking notes.

The Django backend part is no problem for me. But I'm not a web designer. So I'm struggling with the frontend part in the past. That’s the main reason why my Django project don’t go ahead. Maybe together we can change this?!
