### ISSUE TITLE
Getting "The server has encountered a runtime error" when authenticating

### ISSUE THREAD

**Issue by jeromegit** [mkb79/Audible#7]
Hi mkb79,
Thanks for the Python library! 

I was able to use an older version back in July but it started failing when I tried to use it again today.
So, I downloaded the new version (0.2.1 v 0.1.5), made the necessary code changes and I'm still getting the same error.

Here's an abbreviated version of the body of my request:
{'requested_token_type': ['bearer', 'mac_dms', 'website_cookies', 'store_authentication_cookie'], 'cookies': {'website_cookies': [], 'domain': '.amazon.com'}, 'registration_data': {'domain': 'Device', 'app_version': '3.7', 'device_serial': 'Y9UGDIF8OUUKCUF1CHV8M8YZDREDDFM0WOHGDRQV', 'device_type': 'A2CZJZGLK2JJVM', 'device_name': '%FIRST_NAME%%FIRST_NAME_POSSESSIVE_STRING%%DUPE_STRATEGY_1ST%Audible for iPhone', 'os_version': '12.3.1', 'device_model': 'iPhone', 'app_name': 'Audible'}, 'auth_data': {'access_token': 'Atna|EwICID7AOCk...'}, 'requested_extensions': ['device_info', 'customer_info']}

And the return json associated with the 500 HTTP error:
{'request_id': '1fbad2a3-978b-4319-8497-7099f6bc17b3', 'response': {'error': {'code': 'ServerError', 'index': 'xYLIwBnwW...==', 'message': 'The server has encountered a runtime error.'}}}

What am I doing wrong?
Is it a temporary server outage?

Thanks.

**Comment by mkb79** [comment]
Hi jeromegit,

I can‘t reproduce the error you encountered. So far as I understand your error appears during registration process?

Please try this:

```audible

import audible


username = "your-email-for-amazon-login"
password = "your-password"
locale = "your country code (de, fr, ...)"

auth = audible.LoginAuthenticator(username, password, locale)
auth.to_file("geromegit.json", encryption=False)

```

This should register a new device and save the registration object to geromegit.json in script folder.

**Comment by mkb79** [comment]
Can you write me the steps you are done, please? You can write me a pm on reddit also (https://www.reddit.com/user/mkb79)!

**Comment by mkb79** [comment]
@jeromegit 
Can you check your message on reddit please!

**Comment by jeromegit** [comment]
As you suggested, this did the trick to me.
I'm all set.

`import audible

EMAIL = "xxx"
PASSWORD = "yyy"
SESSION_FILE_NAME = "session.json"


locale = audible.localization.Locale('us')
login = audible.login.login(
EMAIL,
PASSWORD,
domain=locale.domain,
countryCode=locale.countryCode,
marketPlaceId=locale.marketPlaceId
)
access_token = login["access_token"]
print(access_token)
profile = audible.auth.user_profile(access_token, locale.domain)
print(profile)
`

**Comment by mkb79** [comment]
Okay, this means you are able to get a `access_token` after a successful authentication.

This can be shorten to:
```
import audible


username = "your-email-for-amazon-login"
password = "your-password"
locale = "your country code (de, fr, ...)"

auth = audible.LoginAuthenticator(
    username, password, locale, register=False)
access_token = auth.access_token
```

Your problems seams to be appears at registration (get adp_token, device_cert, etc.). 

Can you try to register a device with above code and set register=True

**Comment by jeromegit** [comment]
It works perfectly.

Thanks mkb79.

Jérôme  / Blog <http://provensal.com/lbb/> / FB
<https://www.facebook.com/jerome.provensal> / LinkedIn
<http://www.linkedin.com/in/jeromeprovensal> / IG
<http://instagram.com/jeromeig> / Tumblr <http://creativejp.tumblr.com/> /
INTP <http://www.mypersonality.info/personality-types/intp/>
