### ISSUE TITLE
Help with search api

### ISSUE THREAD

**Issue by furbyhaxx** [mkb79/Audible#71]
hi, do you have scraped some info about the api endpoint for searching the marketplace?
I'm not getting the audible app to work with mitmproxy.

**Comment by mkb79** [comment]
Sorry for the Late response. I`m on vacation. 

You can make a GET request (to German marketplace) to https://api.audible.de/1.0/screens/audible-browse/search-ios with following params:

device_type_id= A2CZJZGLK2JJVM
keywords=YOUR_SEARCH_TEXT
customer_id=FILL_OUT
locales=de-DE
session_id=
origin_page= Discover
marketplace= AN7V1F1VY261K

I'm using HTTP Catcher and Audible on my iPhone to get my https traffic. 

Will response more next week when I have more time.

**Comment by afkfurby** [comment]
thanks, will try this. I found some documentation on API endpoints on the "audible-cr" project here on github. but nothing for searching books

**Comment by afkfurby** [comment]
Commenting for reference, maybe making a PR if I have time:
Example for searching via api:
`    with audible.Client(auth=auth) as client:

        resp = client.get(
            "/1.0/catalog/products",
            params={
                "author": "",
                "title": "",
                "keywords" : "Ich bin Viele",
                "narrator": "",
                "publisher": "",
                "num_results": 50,
                "products_sort_by": "Title",  # [-ReleaseDate, ContentLevel, -Title, AmazonEnglish, AvgRating, BestSellers, -RuntimeLength, ReleaseDate, ProductSiteLaunchDate, -ContentLevel, Title, Relevance, RuntimeLength]
                "response_groups": "contributors, media, price, product_attrs, product_desc, product_extended_attrs, product_plans, rating, review_attrs, reviews, sample, sku",
            }
        )`

need to find out how to filter the results by language

**Comment by mkb79** [comment]
Thank you very much for your help. I doesn't know that I can search through the catalog endpoint!

**Comment by afkfurby** [comment]
of course, you can also search the categories endpoint (/1.0/catalog/categories) or directly fetch the infos for a book by "asin" ( /1.0/catalog/products/{asin})

much info about endpoints can be found here: https://github.com/omarroth/audible.cr
.

ah wow, I didn't know that audible has an official api documentation

**Comment by mkb79** [comment]
Yeah. The documentation is collected from many sources with the help from some Github users. I do my best to keep them up to date.

**Comment by afkfurby** [comment]
Thanks for that

**Comment by glitchwizard** [comment]
@afkfurby audible has official docs on their API? Got a link to those?

**Comment by furbyhaxx** [comment]
> @afkfurby audible has official docs on their API? Got a link to those?

sorry, I misunderstood @mkb79, there's no public documentation.

**Comment by mkb79** [comment]
Can someone try PR #70 if it solves the login problem with captchas and approval alerts. For me it's running without any issue.

**Comment by mkb79** [comment]
Yeah, there are no public documentation from Amazon for the Audible API. The API is used by the Audible Apps for mobile devices and Desktop. So the API itself is non public too.

**Comment by furbyhaxx** [comment]
> Yeah, there are no public documentation from Amazon for the Audible API. The API is used by the Audible Apps for mobile devices and Desktop. So the API itself is non public too. 

Will check later today
