### ISSUE TITLE
OTP prompt for 2FA in JupyterLab

### ISSUE THREAD

**Issue by jjf234** [mkb79/Audible#75]
Thanks for creating this package. I'm trying to login over JupyterLab and, although I do get the OTP via text message, the cell throws a "Login failed. Please check the log" error message. That is, the "OTP Code: " prompt does not show up for me in JupyterLab. Is there a workaround or something else I could do instead? Thanks.

**Comment by mkb79** [comment]
That's really strange. You should get your OTP prompt at this point. You can do 2 things now:

When entering your username/password simply add your OTP after your password without empty space in the password field. Make sure your OTP is valid for some seconds. 

You can use the login external mode. Then you login with your browser and follow the text prompt.

**Comment by jjf234** [comment]
Thanks for the help. It feels like I'm getting closer but still no luck. After receiving the OTP and waiting some seconds, I added it to the end of my password then got prompted to answer the CAPTCHA. But the link points to a page that says "This XML file does not appear to have any style information associated with it. The document tree is shown below." and looks like

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
...
</Error>
```

I also tried the login external mode but the link opens up a page that says "We're sorry. The Web address you entered is not a functioning page on our site."  Do you have any more ideas that I could try out?

**Comment by mkb79** [comment]
One thing to the OTP. You are using SMS-OTP or TOTP via App? A SMS-OTP is only valid for the current login session. So if you get them, you have to enter them in the OTP prompt. You can't use them for the next login session. 

I doesn't know why the external link doesn't work for you. Maybe you can send me the given initial link to mkb79@hackitall.de or post your line of codes in the JupyterLab (without your credentials) here?

**Comment by jjf234** [comment]
Resolved offline. For some reason, all of my `&`'s were replaced with `&amp;` in the URLs thus making them malformed. After decoding them back, I was able to complete the login external method successfully. Thanks again for the help.
