### ISSUE TITLE
How does the BestSellers sort_by option in the APIs work?

### ISSUE THREAD

**Issue by Jikeh** [mkb79/Audible#78]
Having a hard time understanding how does the BestSellers option in products_sort_by parameter works, for instance in [/1.0/catalog/products](https://audible.readthedocs.io/en/latest/misc/external_api.html#get-1-0-catalog-products) endpoint. I'm trying to make API calls about the products on audible and sort them by best sellers, yet I'm getting random items in response that are definitely not sorted by best sellers:

`client.get("/1.0/catalog/products", num_results=50, page=0, response_groups=['product_attrs'], products_sort_by=['BestSellers'])`

Am I doing this wrong or is audible just ignoring the parameter?

**Comment by mkb79** [comment]
I doesn't have any experience with these product_sort_by response_group. But I let open this issue. Maybe some other can help.
