### ISSUE TITLE
What are all available "content_type" values?

### ISSUE THREAD

**Issue by jeromegit** [mkb79/Audible#8]
Not really an issue but more like a question.

One of the fields returned when querying my book library is the "content_type".

I would like to find out what are all the potential values associated with that field. 
Based on the content of my own library I see these:

```
Episode                1
Lecture               15
Newspaper / Magazine   2
Performance           12
Product              601
Radio/TV Program       5
Show                   1
Speech                 6
```

Do you have such a list or a way to find such a list?

Thanks!

**Comment by mkb79** [comment]
I really don’t know. But I found the following:

![B8786933-79AD-4B34-A0CE-9DFBEC1B0127](https://user-images.githubusercontent.com/40368641/70409256-6229d700-1a4b-11ea-81c6-27e3abc15cff.png)

**Comment by mkb79** [comment]
Under Program Type must be the content_type.

**Comment by mkb79** [comment]
Forgot to mention it. You can find it [here](https://www.audible.com/advsr).

**Comment by jeromegit** [comment]
Thanks for the quick response, mkb79!
It's good enough for me.
