### ISSUE TITLE
from_login example doesnt match definition

### ISSUE THREAD

**Issue by 89z** [mkb79/Audible#82]
Example has a `register` argument:

https://github.com/mkb79/Audible/blob/f1c7b6ade98bafb3a037d787365e9ba4a3d31f66/examples/get_activation_bytes.py#L14-L18

but function does not:

https://github.com/mkb79/Audible/blob/f1c7b6ade98bafb3a037d787365e9ba4a3d31f66/src/audible/auth.py#L325-L335

**Comment by mkb79** [comment]
Thanks for the information. I corrected it in [this](https://github.com/mkb79/Audible/commit/d5779dbdc42da15fffeb45cf0b37c6b112ff96bc) commit!
