### ISSUE TITLE
Where does the file get stored with to_file()

### ISSUE THREAD

**Issue by normal1ze** [mkb79/Audible#85]
Where does the file get stored? Is there a way I can use `to_file` and `from_file` with a different storage container?

**Comment by mkb79** [comment]
Hi. The `to_file` and `from_file` classmethods take a `pathlib.Path` or string instance to present the file. 

You can add a custom class method to override this behave. If you tell me, what you want to do, I can help you more.

**Comment by normal1ze** [comment]
Ah right. 

Because my instance hosting the library is ephemeral, when it gets scaled the files on the drive are removed and replaced. So I was thinking of storing the file either as blob in DB, blob storage, or in a secure S3 bucket.

**Comment by mkb79** [comment]
You can extend the `Authenticator` class this way:

```python

from audible import Authenticator

class ExtendedAuthenticator(Authenticator):
    @classmethod
    def from_dict(cls, data: dict):
        auth = cls()
        auth.locale = data.pop("locale_code", None)
        if "login_cookies" in data:
            auth.website_cookies = data.pop("login_cookies")
        auth._update_attrs(**data)
        return auth

    def to_dict(self):
        data = {
            "website_cookies": self.website_cookies,
            "adp_token": self.adp_token,
            "access_token": self.access_token,
            "refresh_token": self.refresh_token,
            "device_private_key": self.device_private_key,
            "store_authentication_cookie": self.store_authentication_cookie,
            "device_info": self.device_info,
            "customer_info": self.customer_info,
            "expires": self.expires,
            "locale_code": self.locale.country_code,
            "activation_bytes": self.activation_bytes
        }
        return data
```

Now you have the possibility to export the data as a dict and create a new instance from `ExtendedAuthenticator` from dict! You can now store the data  in a  way you like!

**Comment by normal1ze** [comment]
Oh wow thanks for your help. This is great!!

**Comment by mkb79** [comment]
I‘ve implement this function in audible now. You can test it now with `pip install -i https://test.pypi.org/simple/ audible==0.7.1.dev1`
