### ISSUE TITLE
No categories when using the 

### ISSUE THREAD

**Issue by jeromegit** [mkb79/Audible#9]
Hi mkb79, 
When I use the call/endpoint https://github.com/mkb79/Audible#get-10library the doc indicates that I should get the category/genre associated with each book but it doesn't seem to be the case.

I see "category_ladders" but it's always null for me.

What am I missing?

Thanks!

**Comment by mkb79** [comment]
Hi jeromegit,

my request to the endpoint `1.0/library` with `category_ladders` in response groups give me the following response:

```
'category_ladders': [{'date_product_available_in_category': None, 'ladder': [{'category_presentation': None, 'children': None, 'default_offline_storage_days_count': None, 'default_offline_storage_item_count': None, 'description': None, 'header': None, 'id': '656436031', 'images': None, 'initial_download_days_count': None, 'initial_download_item_count': None, 'is_new': None, 'localized_name': None, 'name': 'Science-Fiction', 'products': None, 'promote_upsell': None, 'suppress_download_option': None, 'suppress_release_date': None}, {'category_presentation': None, 'children': None, 'default_offline_storage_days_count': None, 'default_offline_storage_item_count': None, 'description': None, 'header': None, 'id': '656438031', 'images': None, 'initial_download_days_count': None, 'initial_download_item_count': None, 'is_new': None, 'localized_name': None, 'name': 'Ferne Galaxien', 'products': None, 'promote_upsell': None, 'suppress_download_option': None, 'suppress_release_date': None}], 'root': 'Genres'}]
```

For every book I get the id and name of every step in the category_ladder. 

Greets

**Comment by jeromegit** [comment]
Thanks for the super fast response, mkb79. 
I completely missed that response_groups parameter. I specified product_desc,contributors,product_attrs when I first started using your library and completely forgot about...
RTFM, right?

**Comment by mkb79** [comment]
Yeah, but if you remember to use `response_groups` all wollen fine. 

Greets Marcel
