### ISSUE TITLE
response_callback no longer works properly with the endpoint:  https://cde-ta-g7g.amazon.com/FionaCDEServiceEngine/sidecar 

### ISSUE THREAD

**Issue by GGyll** [mkb79/Audible#99]
**Describe the bug**
Using the `https://cde-ta-g7g.amazon.com/FionaCDEServiceEngine/sidecar` worked previously with `audible.Client` and returned the correct response. Now it returns None. In `client.py Client._request()` the `resp `object contains the correct response however the `response_callback()` function returns None with the `resp `object, hence this endpoint is unusable.

This is because
in `default_response_callback` `resp.next_request` returns None for this endpoint

**To Reproduce**
```
auth = audible.Authenticator.from_file("credentials.json")
def get_bookmarks(url, **kwargs):
    with audible.Client(auth=auth) as client:
        library = client.get(
            url,
            **kwargs
        )
        return library

```

**Expected behavior**
Returns the clips, notes and bookmarks of a book

**Desktop (please complete the following information):**
audible==0.8.2
Python 3.10.1

**Comment by GGyll** [comment]
Thanks for the fast response. 
I actually had those query parameters but had hardcoded them into the URL like so 
`f"https://cde-ta-g7g.amazon.com/FionaCDEServiceEngine/sidecar?type=AUDI&key={ASIN}"`

`ASIN = "1473565421"`

Still with your solution I get None object, having a custom_callback gives me the dictionary I want, but you said this isn't a solution?

```
My code:
def get_bookmarks(url, asin, **kwargs):
    with audible.Client(auth=auth) as client:
        params = {
            "type": "AUDI",
            "key": asin
        }
        library = client.get(
            url,
            params=params,
            **kwargs
        )
        return library
```
```
bookmarks_url = "https://cde-ta-g7g.amazon.com/FionaCDEServiceEngine/sidecar"
bookmarks_dict = get_bookmarks(bookmarks_url, ASIN)
```

**Comment by mkb79** [comment]
> Still with your solution I get None object, having a custom_callback gives me the dictionary I want, but you said this isn't a solution?

I thought you provide the url without the params. If I understood you correctly, you've got `None` with the default callback and the dict, with your custom callback for the same asin?

The default callback is the following:

```python
def default_response_callback(resp: httpx.Response) -> Union[Dict, str]:
    raise_for_status(resp)
    return convert_response_content(resp)


def raise_for_status(resp: httpx.Response) -> None:
    try:
        resp.raise_for_status()
    except httpx.HTTPStatusError as e:
        code = resp.status_code
        data = convert_response_content(resp)
        if code == 400:
            raise BadRequest(resp, data) from None
        elif code in (401, 403):  # Unauthorized request - Invalid credentials
            raise Unauthorized(resp, data) from None
        elif code == 404:  # not found
            raise NotFoundError(resp, data) from None
        elif code == 429:
            raise RatelimitError(resp, data) from None
        elif code == 503:  # Maintainence
            raise ServerError(resp, data) from None
        else:
            raise UnexpectedError(resp, data) from e


def convert_response_content(resp: httpx.Response) -> Union[Dict, str]:
    try:
        return resp.json()
    except json.JSONDecodeError:
        return resp.text
```

First it make sure, that the response has a status code 200 <= code < 300. Otherwise it will raise an exception. Is an exception Is raised for you?

If the status code is in the allowed range, it will try to read the json string and convert it to a dict. If this fails, it will return the text. So you should got something (dict, str or exception) but not None.

**Comment by mkb79** [comment]
FYI:
I've got a response with the default callback or a 404 exception, if the asin has no bookmarks.
